### ISSUE TITLE
这个mpls好像提取不了chapter？

### ISSUE THREAD

**Issue by fireattack** [tautcony/ChapterTool#1]
[00002.zip](https://github.com/tautcony/ChapterTool/files/1484304/00002.zip)

**Comment by tautcony** [comment]
如果没有猜错的话，应该`[00003-00009].m2ts`合起来才是一集，你需要在右上角片段选择那边右键选择合并章节。

**Comment by fireattack** [comment]
原来还有右键菜单，学习了

另外，右下角的progress bar一直卡在未完成的状态感觉怪怪的

![image](https://user-images.githubusercontent.com/4130991/32976613-0098f7fc-cbe0-11e7-94a8-d20f52f42aa1.png)

**Comment by tautcony** [comment]
哦，那个是和我奇怪的逻辑相对的，保存了才算100%完成（
