### ISSUE TITLE
无法打开MP4文件

### ISSUE THREAD

**Issue by fireattack** [tautcony/ChapterTool#3]
Win7x64

mp4v2.dll是从这里下载的：https://code.google.com/archive/p/mp4v2/downloads （mp4v2-r479-windows-binaries.zip）放在ChapterTool.v2.33.33.33.exe同一目录应该就行了吧？（x64和x86的dll都试了）

报错如下

```
   在 Knuckleball.NativeMethods.MP4Read(String fileName)
   在 Knuckleball.MP4File.Load()
   在 ChapterTool.Util.ChapterData.Mp4Data..ctor(String path)
   在 ChapterTool.Forms.Form1.LoadMp4()
```

**Comment by tautcony** [comment]
看了一下，`2.33.33.33`编译的时候被`VS`默认选了`Any CPU`的选项，~~结果就什么dll都不肯加载了~~（是由于x64的dll载入本来就是有问题的），已经重新使用`x86`作为`target`重新编译，烦请重新[下载](https://github.com/tautcony/ChapterTool/releases/download/2.33.33.33/ChapterTool.v2.33.33.33.exe)试一下。

**Comment by fireattack** [comment]
可以了，多谢！
