### ISSUE TITLE
Add English Language

### ISSUE THREAD

**Issue by xmha97** [tautcony/ChapterTool#4]
Hello, I don't understand the Chinese language.
Please add the English language
Thanks.

**Comment by tautcony** [comment]
This tool actually supports English(If you compile this project yourself).

I have just uploaded a complete package with all files required named as `ChapterTool.v2.33.33.33-full.7z` to [this page](https://github.com/tautcony/ChapterTool/releases/tag/2.33.33.33).

you can find language switch button by clicking icon at upper left corner which is named as 'Switch language'.

---

For translate improvement, feel free to submit pull request.

**Comment by xmha97** [comment]
Ok, Thanks very much

![image](https://user-images.githubusercontent.com/23485114/70114715-a47d9d80-1672-11ea-954a-fa98695597af.png)

**Comment by galantra** [comment]
An info for other users:

For the `switch language` button, you need to click on the black square that has `CT _ ` on it.

It's simple but took me some time to figure out since I am not used to buttons hidden in this place.
