### ISSUE TITLE
Windows: Unable to open files

### ISSUE THREAD

**Issue by rokdd** [tautcony/ChapterTool#5]
I am not able to open any file from Windows like from the Download Directory. What I might doing wrong?

![image](https://user-images.githubusercontent.com/640866/71560643-322f8b80-2a6d-11ea-9deb-3a6dae0b7b2d.png)

**Comment by tautcony** [comment]
TL;DR
You could run this program as Administrator or move file to `D:\path\to\your\movie.mp4`.

----

The `.mp4` format is now handled by libmp4v2, and it's api required an ANSI file name to make it work properly.
To make some file such as `けいおん！！.mp4` could load correctly, I made a workaround by creating a temporary hard link for the `.mp4` file at root directory where file located, in this issue's case, the program would try to create a hard link like this: `C:\ba2c0af9-75fa-4d6b-b881-24b38d5d6f6f`, `C:\`! It's a **system partition** and lead to a **permission issue**.

**Comment by rokdd** [comment]
It worked.. but the application was not usable for my tasks :-( . Thank you anyway
