### ISSUE TITLE
JSON Format Error

### ISSUE THREAD

**Issue by Totto16** [tautcony/ChapterTool#8]
In "Time_Shift/Util/ChapterInfo.cs" line 387 there is an error regarding the JSON formatting, it should be `{(time.TotalSeconds).Replace(",",".")}` instead of `{time.TotalSeconds}`. As in The JSON Standard declared, JSON fields without Quotation can't have "," in it, beacuse a "," declares the separation. As The TimeSpan.TotalSeconds return value contains a "," instead of a "." it has to be replaced by a dot. If not the JSON is invalid.

**Comment by tautcony** [comment]
Confirmed.

**Comment by tautcony** [comment]
Fixed, actually I didn’t expect someone would use this output format, haha.
